In [1]:
import torch

In [18]:
a = torch.nn.Embedding(100, 100)
b = torch.nn.Embedding(100, 100)
c = torch.nn.Linear(100, 100)
d = torch.nn.Parameter(torch.randn((100,100)))

In [16]:
torch.randn(100,100).shape

torch.Size([100, 100])

In [17]:
torch.randn((100,100)).shape

torch.Size([100, 100])

In [3]:
a = torch.randn(10,5,3)
b = torch.randn(10,5,3)

In [11]:
torch.cat([a, b], dim=-1).shape

torch.Size([10, 5, 6])

In [46]:
a.weight = d
b.weight = d
c.weight = d

In [49]:
a.weight

Parameter containing:
tensor([[-1.8538, -0.3930, -2.3039,  ...,  1.9179, -1.0638, -0.6847],
        [ 0.1682,  1.9091,  0.5374,  ...,  1.4815, -0.2173,  0.3503],
        [ 0.0810,  0.8284, -0.8905,  ...,  0.9841, -1.3972,  0.4104],
        ...,
        [-0.4602,  1.5924, -1.4398,  ...,  0.5025,  2.5260,  1.0231],
        [-1.6919,  0.0265,  0.3815,  ..., -0.6243, -0.7998, -0.9686],
        [ 1.2108,  0.1464, -0.2416,  ..., -2.6398,  0.0199, -0.8723]],
       requires_grad=True)

In [12]:
b.weight

AttributeError: 'Tensor' object has no attribute 'weight'

In [48]:
c.weight

Parameter containing:
tensor([[-1.8538, -0.3930, -2.3039,  ...,  1.9179, -1.0638, -0.6847],
        [ 0.1682,  1.9091,  0.5374,  ...,  1.4815, -0.2173,  0.3503],
        [ 0.0810,  0.8284, -0.8905,  ...,  0.9841, -1.3972,  0.4104],
        ...,
        [-0.4602,  1.5924, -1.4398,  ...,  0.5025,  2.5260,  1.0231],
        [-1.6919,  0.0265,  0.3815,  ..., -0.6243, -0.7998, -0.9686],
        [ 1.2108,  0.1464, -0.2416,  ..., -2.6398,  0.0199, -0.8723]],
       requires_grad=True)

In [54]:
with torch.no_grad():
    a.weight[1] -= torch.ones_like(a.weight[1])

In [55]:
a.weight

Parameter containing:
tensor([[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [-0.8318,  0.9091, -0.4626,  ...,  0.4815, -1.2173, -0.6497],
        [ 0.0810,  0.8284, -0.8905,  ...,  0.9841, -1.3972,  0.4104],
        ...,
        [-0.4602,  1.5924, -1.4398,  ...,  0.5025,  2.5260,  1.0231],
        [-1.6919,  0.0265,  0.3815,  ..., -0.6243, -0.7998, -0.9686],
        [ 1.2108,  0.1464, -0.2416,  ..., -2.6398,  0.0199, -0.8723]],
       requires_grad=True)

In [56]:
b.weight

Parameter containing:
tensor([[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [-0.8318,  0.9091, -0.4626,  ...,  0.4815, -1.2173, -0.6497],
        [ 0.0810,  0.8284, -0.8905,  ...,  0.9841, -1.3972,  0.4104],
        ...,
        [-0.4602,  1.5924, -1.4398,  ...,  0.5025,  2.5260,  1.0231],
        [-1.6919,  0.0265,  0.3815,  ..., -0.6243, -0.7998, -0.9686],
        [ 1.2108,  0.1464, -0.2416,  ..., -2.6398,  0.0199, -0.8723]],
       requires_grad=True)

In [57]:
c.weight

Parameter containing:
tensor([[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [-0.8318,  0.9091, -0.4626,  ...,  0.4815, -1.2173, -0.6497],
        [ 0.0810,  0.8284, -0.8905,  ...,  0.9841, -1.3972,  0.4104],
        ...,
        [-0.4602,  1.5924, -1.4398,  ...,  0.5025,  2.5260,  1.0231],
        [-1.6919,  0.0265,  0.3815,  ..., -0.6243, -0.7998, -0.9686],
        [ 1.2108,  0.1464, -0.2416,  ..., -2.6398,  0.0199, -0.8723]],
       requires_grad=True)

In [58]:
a

Embedding(100, 100)

In [59]:
c

Linear(in_features=100, out_features=100, bias=True)

In [62]:
aa = torch.arange(0,10)

In [63]:
-aa

tensor([ 0, -1, -2, -3, -4, -5, -6, -7, -8, -9])

In [67]:
torch.exp(2*torch.log(aa[1:]))

tensor([ 1.0000,  4.0000,  9.0000, 16.0000, 25.0000, 36.0000, 49.0000, 64.0000,
        81.0000])

In [68]:
aa[1:]**2

tensor([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [4]:
max_len = 128
dim = 512

dim_loc = torch.arange(start=0, end=dim, step=2)
pos_loc = torch.arange(start=0, end=max_len, step=1)
pos_enc = torch.zeros((max_len, dim))

denominator = torch.exp((-(dim_loc/dim))*(torch.log(torch.tensor(10000))))
sin_pe = torch.sin(pos_loc.unsqueeze(1)*denominator.unsqueeze(0))
cos_pe = torch.cos(pos_loc.unsqueeze(1)*denominator.unsqueeze(0))

pos_enc[:,0::2] = sin_pe
pos_enc[:,1::2] = cos_pe

In [7]:
denominator.shape

torch.Size([256])

In [8]:
sin_pe.shape

torch.Size([128, 256])

In [11]:
aa = torch.rand((10,128,512))
bb = torch.rand((128,512))

In [2]:
aa = torch.Tensor([[True, True, True, False, False],
                   [True, True, False, False, False],
                   [True, True, True, True, False]])

# aa = torch.Tensor([[False, False, False, True, True],
#                    [False, False, True, True, True],
#                    [False, False, False, False, True]]) 

In [3]:
mask = (torch.bmm(aa.unsqueeze(2), aa.unsqueeze(1)) == 0)

In [4]:
testtensor = torch.randn(mask.shape)

In [5]:
mask

tensor([[[False, False, False,  True,  True],
         [False, False, False,  True,  True],
         [False, False, False,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True]],

        [[False, False,  True,  True,  True],
         [False, False,  True,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True]],

        [[False, False, False, False,  True],
         [False, False, False, False,  True],
         [False, False, False, False,  True],
         [False, False, False, False,  True],
         [ True,  True,  True,  True,  True]]])

In [6]:
(torch.triu(torch.ones_like(mask), 1) != 0)

tensor([[[False,  True,  True,  True,  True],
         [False, False,  True,  True,  True],
         [False, False, False,  True,  True],
         [False, False, False, False,  True],
         [False, False, False, False, False]],

        [[False,  True,  True,  True,  True],
         [False, False,  True,  True,  True],
         [False, False, False,  True,  True],
         [False, False, False, False,  True],
         [False, False, False, False, False]],

        [[False,  True,  True,  True,  True],
         [False, False,  True,  True,  True],
         [False, False, False,  True,  True],
         [False, False, False, False,  True],
         [False, False, False, False, False]]])

In [22]:
masked_info = (torch.bmm(aa.unsqueeze(2), aa.unsqueeze(1)) == 0)
# leftward_mask = (torch.triu(torch.ones_like(masked_info), 1) != 0)
leftward_mask = (torch.triu(torch.ones_like(mask), 1) != 0)
masked_info = masked_info | leftward_mask

In [23]:
masked_info

tensor([[[False,  True,  True,  True,  True],
         [False, False,  True,  True,  True],
         [False, False, False,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True]],

        [[False,  True,  True,  True,  True],
         [False, False,  True,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True]],

        [[False,  True,  True,  True,  True],
         [False, False,  True,  True,  True],
         [False, False, False,  True,  True],
         [False, False, False, False,  True],
         [ True,  True,  True,  True,  True]]])

In [8]:
masked_info.shape

torch.Size([3, 5, 5])

In [52]:
score = testtensor.masked_fill_(masked_info, float("-inf")).softmax(-1).nan_to_num_(0)

In [64]:
tt = torch.randn(3,5,10)

In [65]:
score

tensor([[[1.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.9270, 0.0730, 0.0000, 0.0000, 0.0000],
         [0.1853, 0.6752, 0.1395, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000]],

        [[1.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.8933, 0.1067, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000]],

        [[1.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.1153, 0.8847, 0.0000, 0.0000, 0.0000],
         [0.0389, 0.5638, 0.3973, 0.0000, 0.0000],
         [0.3896, 0.0410, 0.2906, 0.2788, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000]]])

In [68]:
-1.0417*0.9270 + -0.3332*0.0730

-0.9899795000000001

In [66]:
tt[0]

tensor([[-1.0417,  0.7163,  0.5321, -0.0333,  1.3315,  0.0437, -0.2938, -0.5395,
         -0.6646,  0.0641],
        [-0.3332,  0.1088, -0.0375, -0.6287,  0.1709,  0.4036, -1.6860,  1.3272,
         -1.0738,  0.9710],
        [-0.6871, -0.5298, -0.6686,  0.5839,  0.4873, -0.7931,  1.0659,  1.6977,
         -0.0415, -1.1701],
        [-0.2060, -0.1422, -0.3656,  2.1778,  1.1547, -0.1985, -1.2704,  0.4518,
         -1.0347, -0.8487],
        [-0.2407,  1.2122, -0.6281,  0.5664, -0.5735,  0.4620, -0.6485,  0.1251,
         -0.9695,  0.9958]])

In [69]:
torch.bmm(score, tt).shape

torch.Size([3, 5, 10])

In [30]:
masked_info

tensor([[[False, False, False,  True,  True],
         [ True, False, False,  True,  True],
         [ True,  True, False,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True]],

        [[False, False,  True,  True,  True],
         [ True, False,  True,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True]],

        [[False, False, False, False,  True],
         [ True, False, False, False,  True],
         [ True,  True, False, False,  True],
         [ True,  True,  True, False,  True],
         [ True,  True,  True,  True,  True]]])

In [38]:
test = torch.tensor([[2,1,2,0,0],
                     [1,2,0,0,0],
                     [1,0,0,0,0]])

In [43]:
test[test != 0] = 1

In [44]:
test

tensor([[1, 1, 1, 0, 0],
        [1, 1, 0, 0, 0],
        [1, 0, 0, 0, 0]])

In [13]:
import torch
masked_info = torch.randn(10, 5, 5)
aa = (torch.triu(torch.ones_like(masked_info), 1) != 0)

In [16]:
aa[0]

tensor([[False,  True,  True,  True,  True],
        [False, False,  True,  True,  True],
        [False, False, False,  True,  True],
        [False, False, False, False,  True],
        [False, False, False, False, False]])

In [37]:
src = torch.tensor([[1,1,0,0]])
tgt = torch.tensor([[1,1,1,0]])
src.shape

torch.Size([1, 4])

In [38]:
src_m = torch.bmm(src.unsqueeze(2), src.unsqueeze(1))
tgt_m = torch.bmm(tgt.unsqueeze(2), tgt.unsqueeze(1))

In [51]:
(torch.bmm(tgt_m, src_m) != 0)

tensor([[[ True,  True, False, False],
         [ True,  True, False, False],
         [ True,  True, False, False],
         [False, False, False, False]]])

In [44]:
src = torch.randn(1,4,7)
tgt = torch.randn(1,4,7)
src[:,2:,:] = 0
tgt[:,3:,:] = 0

In [45]:
src

tensor([[[-0.7080, -0.2907,  0.3386, -1.3895,  0.4269, -0.6593, -0.0395],
         [ 1.3741, -0.0940, -0.1555,  0.5871,  2.0669,  1.2533, -1.4059],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000]]])

In [46]:
torch.bmm(tgt, src.permute(0,2,1))

tensor([[[-2.3459, -1.3855,  0.0000,  0.0000],
         [ 0.3843, -4.5679,  0.0000,  0.0000],
         [ 1.8576, -1.8814,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000]]])