In [1]:
import torch

In [44]:
a = torch.nn.Embedding(100, 100)
b = torch.nn.Embedding(100, 100)
c = torch.nn.Linear(100, 100)
d = torch.nn.Parameter(torch.randn((100,100)))

In [46]:
a.weight = d
b.weight = d
c.weight = d

In [49]:
a.weight

Parameter containing:
tensor([[-1.8538, -0.3930, -2.3039,  ...,  1.9179, -1.0638, -0.6847],
        [ 0.1682,  1.9091,  0.5374,  ...,  1.4815, -0.2173,  0.3503],
        [ 0.0810,  0.8284, -0.8905,  ...,  0.9841, -1.3972,  0.4104],
        ...,
        [-0.4602,  1.5924, -1.4398,  ...,  0.5025,  2.5260,  1.0231],
        [-1.6919,  0.0265,  0.3815,  ..., -0.6243, -0.7998, -0.9686],
        [ 1.2108,  0.1464, -0.2416,  ..., -2.6398,  0.0199, -0.8723]],
       requires_grad=True)

In [47]:
b.weight

Parameter containing:
tensor([[-1.8538, -0.3930, -2.3039,  ...,  1.9179, -1.0638, -0.6847],
        [ 0.1682,  1.9091,  0.5374,  ...,  1.4815, -0.2173,  0.3503],
        [ 0.0810,  0.8284, -0.8905,  ...,  0.9841, -1.3972,  0.4104],
        ...,
        [-0.4602,  1.5924, -1.4398,  ...,  0.5025,  2.5260,  1.0231],
        [-1.6919,  0.0265,  0.3815,  ..., -0.6243, -0.7998, -0.9686],
        [ 1.2108,  0.1464, -0.2416,  ..., -2.6398,  0.0199, -0.8723]],
       requires_grad=True)

In [48]:
c.weight

Parameter containing:
tensor([[-1.8538, -0.3930, -2.3039,  ...,  1.9179, -1.0638, -0.6847],
        [ 0.1682,  1.9091,  0.5374,  ...,  1.4815, -0.2173,  0.3503],
        [ 0.0810,  0.8284, -0.8905,  ...,  0.9841, -1.3972,  0.4104],
        ...,
        [-0.4602,  1.5924, -1.4398,  ...,  0.5025,  2.5260,  1.0231],
        [-1.6919,  0.0265,  0.3815,  ..., -0.6243, -0.7998, -0.9686],
        [ 1.2108,  0.1464, -0.2416,  ..., -2.6398,  0.0199, -0.8723]],
       requires_grad=True)

In [54]:
with torch.no_grad():
    a.weight[1] -= torch.ones_like(a.weight[1])

In [55]:
a.weight

Parameter containing:
tensor([[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [-0.8318,  0.9091, -0.4626,  ...,  0.4815, -1.2173, -0.6497],
        [ 0.0810,  0.8284, -0.8905,  ...,  0.9841, -1.3972,  0.4104],
        ...,
        [-0.4602,  1.5924, -1.4398,  ...,  0.5025,  2.5260,  1.0231],
        [-1.6919,  0.0265,  0.3815,  ..., -0.6243, -0.7998, -0.9686],
        [ 1.2108,  0.1464, -0.2416,  ..., -2.6398,  0.0199, -0.8723]],
       requires_grad=True)

In [56]:
b.weight

Parameter containing:
tensor([[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [-0.8318,  0.9091, -0.4626,  ...,  0.4815, -1.2173, -0.6497],
        [ 0.0810,  0.8284, -0.8905,  ...,  0.9841, -1.3972,  0.4104],
        ...,
        [-0.4602,  1.5924, -1.4398,  ...,  0.5025,  2.5260,  1.0231],
        [-1.6919,  0.0265,  0.3815,  ..., -0.6243, -0.7998, -0.9686],
        [ 1.2108,  0.1464, -0.2416,  ..., -2.6398,  0.0199, -0.8723]],
       requires_grad=True)

In [57]:
c.weight

Parameter containing:
tensor([[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [-0.8318,  0.9091, -0.4626,  ...,  0.4815, -1.2173, -0.6497],
        [ 0.0810,  0.8284, -0.8905,  ...,  0.9841, -1.3972,  0.4104],
        ...,
        [-0.4602,  1.5924, -1.4398,  ...,  0.5025,  2.5260,  1.0231],
        [-1.6919,  0.0265,  0.3815,  ..., -0.6243, -0.7998, -0.9686],
        [ 1.2108,  0.1464, -0.2416,  ..., -2.6398,  0.0199, -0.8723]],
       requires_grad=True)

In [58]:
a

Embedding(100, 100)

In [59]:
c

Linear(in_features=100, out_features=100, bias=True)

In [62]:
aa = torch.arange(0,10)

In [63]:
-aa

tensor([ 0, -1, -2, -3, -4, -5, -6, -7, -8, -9])

In [67]:
torch.exp(2*torch.log(aa[1:]))

tensor([ 1.0000,  4.0000,  9.0000, 16.0000, 25.0000, 36.0000, 49.0000, 64.0000,
        81.0000])

In [68]:
aa[1:]**2

tensor([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [4]:
max_len = 128
dim = 512

dim_loc = torch.arange(start=0, end=dim, step=2)
pos_loc = torch.arange(start=0, end=max_len, step=1)
pos_enc = torch.zeros((max_len, dim))

denominator = torch.exp((-(dim_loc/dim))*(torch.log(torch.tensor(10000))))
sin_pe = torch.sin(pos_loc.unsqueeze(1)*denominator.unsqueeze(0))
cos_pe = torch.cos(pos_loc.unsqueeze(1)*denominator.unsqueeze(0))

pos_enc[:,0::2] = sin_pe
pos_enc[:,1::2] = cos_pe

In [7]:
denominator.shape

torch.Size([256])

In [8]:
sin_pe.shape

torch.Size([128, 256])

In [11]:
aa = torch.rand((10,128,512))
bb = torch.rand((128,512))

In [2]:
aa = torch.Tensor([[True, True, True, False, False],
                   [True, True, False, False, False],
                   [True, True, True, True, False]])

In [3]:
mask = torch.bmm(aa.unsqueeze(2), aa.unsqueeze(1))

In [23]:
testtensor = torch.randn(mask.shape)

In [8]:
mask

tensor([[[1., 1., 1., 0., 0.],
         [1., 1., 1., 0., 0.],
         [1., 1., 1., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[1., 1., 0., 0., 0.],
         [1., 1., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[1., 1., 1., 1., 0.],
         [1., 1., 1., 1., 0.],
         [1., 1., 1., 1., 0.],
         [1., 1., 1., 1., 0.],
         [0., 0., 0., 0., 0.]]])

In [47]:
(torch.triu(torch.ones_like(mask), 1) != 0)

tensor([[[False,  True,  True,  True,  True],
         [False, False,  True,  True,  True],
         [False, False, False,  True,  True],
         [False, False, False, False,  True],
         [False, False, False, False, False]],

        [[False,  True,  True,  True,  True],
         [False, False,  True,  True,  True],
         [False, False, False,  True,  True],
         [False, False, False, False,  True],
         [False, False, False, False, False]],

        [[False,  True,  True,  True,  True],
         [False, False,  True,  True,  True],
         [False, False, False,  True,  True],
         [False, False, False, False,  True],
         [False, False, False, False, False]]])

In [50]:
masked_info = torch.bmm((aa).unsqueeze(2), (aa).unsqueeze(1))
# leftward_mask = (torch.triu(torch.ones_like(masked_info), 1) != 0)
leftward_mask = (torch.triu(torch.ones_like(masked_info)) == 0)
masked_info = (masked_info == 0) | leftward_mask

In [51]:
masked_info

tensor([[[False, False, False,  True,  True],
         [ True, False, False,  True,  True],
         [ True,  True, False,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True]],

        [[False, False,  True,  True,  True],
         [ True, False,  True,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True]],

        [[False, False, False, False,  True],
         [ True, False, False, False,  True],
         [ True,  True, False, False,  True],
         [ True,  True,  True, False,  True],
         [ True,  True,  True,  True,  True]]])

In [49]:
masked_info

tensor([[[False,  True,  True,  True,  True],
         [False, False,  True,  True,  True],
         [False, False, False,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True]],

        [[False,  True,  True,  True,  True],
         [False, False,  True,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True]],

        [[False,  True,  True,  True,  True],
         [False, False,  True,  True,  True],
         [False, False, False,  True,  True],
         [False, False, False, False,  True],
         [ True,  True,  True,  True,  True]]])

In [30]:
masked_info

tensor([[[False, False, False,  True,  True],
         [ True, False, False,  True,  True],
         [ True,  True, False,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True]],

        [[False, False,  True,  True,  True],
         [ True, False,  True,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True]],

        [[False, False, False, False,  True],
         [ True, False, False, False,  True],
         [ True,  True, False, False,  True],
         [ True,  True,  True, False,  True],
         [ True,  True,  True,  True,  True]]])

In [38]:
test = torch.tensor([[2,1,2,0,0],
                     [1,2,0,0,0],
                     [1,0,0,0,0]])

In [43]:
test[test != 0] = 1

In [44]:
test

tensor([[1, 1, 1, 0, 0],
        [1, 1, 0, 0, 0],
        [1, 0, 0, 0, 0]])